name = "tokengoblin-api"
main = "src/worker.js"
compatibility_date = "2024-06-01"

[vars]
ENVIRONMENT = "production"
APP_NAME = "tokengoblin"
LOG_LEVEL = "INFO"

[[d1_databases]]
binding = "DB"
database_name = "token_goblin"
database_id = "b3498282-4c1a-43cc-9500-c4af38bd0071"

[[routes]]
pattern = "tokengoblin.example.com"
custom_domain = true
